server:
  port: 18081

management:
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/racket?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      username: suyeon
      password: racket
      driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: 1234
      connectionString: mongodb://root:1234@localhost:27017

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        hbm2ddl.auto: update
    open-in-view: false
    show-sql: true

  redis:
    host: 127.0.0.1
    password: 1234
    port: 6379
  session:
    store-type: redis

  config:
    import: swagger.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


client:
  serviceUrl:
    producer:  http://localhost:18082/produce/v1
    product: localhost:18081/api/v1/product